THEOREMS = [' |- (A|(A&B))->A', 
        ' |- (A&(A|B))->A', 
        ' |- (A->(B->C))->(B->(A->C))', 
        ' |- (A->(A->B))->(A->B)', 
        ' |- (~A->B)->((~A->~B)->A)', 
        ' |- A|~A', 
        ' |- (A->B)|(B->A)', 
        ' |- A->A', 
        ' |- (A->B)->((C->A)->(C->A))', 
        'A&B->C |- B->(A->C)', 
        'B->(A->C) |- A&B->C', 
        ' |- (A->(B->C))->((A->B)->(A->C))', 
        ' |- A->(B->A)', 
        ' |- ((A->B)->A)->A', 
        'A->C, A|B, B->C |- C', 
        'A |- ~~A', '~~A |- A', 
        'A->B, ~B |- ~A', 
        '~B->~A |- A->B', 
        'A->B |- ~B->~A', 
        '~(A|B) |- ~A&~B', 
        '~A&~B |- ~(A|B)', 
        '~(A&B) |- ~A|~B', 
        '~A|~B |- ~(A&B)', 
        'A|(B&C) |- (A|B)&(A|C)', 
        '(A|B)&(A|C) |- A|(B&C)', 
        'A&(B|C) |- (A&B)|(A&C)', 
        '(A&B)|(A&C) |- A&(B|C)', 
        'A|B, ~B |- A', 
        'A|B |- ~A->B', 
        '~A->B |- A|B', 
        'A&B |- ~(A->~B)', 
        '~(A->~B) |- A&B', 
        'A|B |- ~(~A&~B)', 
        '~(~A&~B) |- A|B', 
        'A->B |- ~(A&~B)', 
        '~(A&~B) |- A->B', 
        'A&B |- ~(~A|~B)', 
        '~(~A|~B) |- A&B', 
        'A->B |- ~A|B', 
        '~A|B |- A->B', 
        ' |- Ax P(x)->~Ex ~P(x)', 
        ' |- ~Ex ~P(x)->Ax P(x)',  
        ' |- Ex P(x)->~Ax ~P(x)', 
        ' |- ~Ax ~P(x)->Ex P(x)', 
        ' |- Ax (P(x)&Q(x))->(Ax P(x)&Ax Q(x))', 
        ' |- Ax Ay P(x,y)->Ay Ax P(x,y)', 
        ' |- Ax (P->Q(x))->(P->Ax Q(x))', 
        ' |- Ex (P(x)|Q(x))->(Ex P(x)|Ex Q(x))', 
        ' |- ~Ax P(x)->Ex ~P(x)', 
        ' |- Ex ~P(x)->~Ax P(x)', 
        ' |- ~Ex P(x)->Ax ~P(x)', 
        ' |- Ax ~P(x)->~Ex P(x)', 
        ' |- Ex (P(x)&Q)->(Ex P(x)&Q)', 
        ' |- (Ex P(x)&Q)->Ex (P(x)&Q)', 
        ' |- Ax (P(x)|Q)->(Ax P(x)|Q)', 
        ' |- (Ax P(x)|Q)->Ax (P(x)|Q)', 
        ' |- Ex (P(x)->Q)->(Ax P(x)->Q)', 
        ' |- (Ax P(x)->Q)->Ex (P(x)->Q)', 
        ' |- Ex (P->Q(x))->(P->Ex Q(x))', 
        ' |- (P->Ex Q(x))->Ex (P->Q(x))', 
        ' |- Ex (P(x)->Ax P(x))'
        ]
